In [1]:
import nltk
nltk.download('punkt')
from nltk import word_tokenize
from collections import Counter
from nltk.corpus import stopwords
nltk.download('stopwords')
import pandas as pd
from sklearn.model_selection import train_test_split

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ACER\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ACER\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [20]:
data = pd.read_csv('twitter_training.csv')

In [21]:
data.columns

Index(['2401', 'Borderlands', 'Positive',
       'im getting on borderlands and i will murder you all ,'],
      dtype='object')

In [22]:
data = data.rename(columns={'2401': 'id', 'Borderlands': 'provider', 'Positive': 'target',
                            'im getting on borderlands and i will murder you all ,':'text'})


In [23]:
data.head()

id     provider    target  \
0  2401  Borderlands  Positive   
1  2401  Borderlands  Positive   
2  2401  Borderlands  Positive   
3  2401  Borderlands  Positive   
4  2401  Borderlands  Positive   

                                                text  
0  I am coming to the borders and I will kill you...  
1  im getting on borderlands and i will kill you ...  
2  im coming on borderlands and i will murder you...  
3  im getting on borderlands 2 and i will murder ...  
4  im getting into borderlands and i can murder y...

In [26]:
data.isna().sum()

id          0
provider    0
target      0
text        0
dtype: int64

In [25]:
data = data.dropna(subset=['text'])

In [27]:
X = data['text']
y = data['target']
#y = data['Party'].map({'positive':1,'negative':0})

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.30,shuffle=True) # shuffle = aleatorio

In [29]:
X_train.shape

(51796,)

In [30]:
from sklearn.feature_extraction.text import CountVectorizer

In [31]:
count_vector = CountVectorizer(stop_words='english',ngram_range=(1,7))

In [32]:
# Normalizando los datos de texto
X_train_count = count_vector.fit_transform(X_train.values)
X_test_count = count_vector.transform(X_test.values) # Test no se fittea, no se entrena, solo se transforma

## Naive Bayes classifier model 

In [33]:
from sklearn.naive_bayes import MultinomialNB

In [34]:
model = MultinomialNB() # Modelo naive bayes, a partir de una serie de caracteristicas, se le asigna una etiqueta

In [35]:
model.fit(X_train_count, y_train)
y_pred = model.predict(X_test_count)

In [36]:
X_train_count

<51796x1503033 sparse matrix of type '<class 'numpy.int64'>'
	with 2749749 stored elements in Compressed Sparse Row format>

In [37]:
print(y_pred)

['Negative' 'Positive' 'Positive' ... 'Neutral' 'Negative' 'Negative']


In [38]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [39]:
print(accuracy_score(y_test,y_pred))

0.9045452497860264


In [40]:
print(confusion_matrix(y_test,y_pred))

[[3214  343   85  248]
 [  20 6391  114  145]
 [  15  397 4911  167]
 [  21  422  142 5564]]
